receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: info
  awsxray:
  prometheus:
    endpoint: 0.0.0.0:9090
  zipkin:
    endpoint: "http://zipkin-server:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger-server:14250
    insecure: true
processors:
  memory_limiter:
    limit_mib: 100
    check_interval: 5s
service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - logging
      - awsxray
      - zipkin
      - jaeger
    metrics:
      receivers:
      - otlp
      exporters:
      - prometheus
