receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9100
exporters:
  logging:
    loglevel: info
  awsxray:
    local_mode: true
  zipkin:
    endpoint: "http://zipkin-server:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger-server:14250
    insecure: true
service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - logging
      - awsxray
      - zipkin
      - jaeger
